@startuml

  Class Mundo{
    +Mundo(string nombre_mundo): nombre_mundo(nombre_mundo);
    +string nombre_mundo;
  }

  abstract Class Personaje{
    +string nombre;
    +int telefono;
    +Mundo* mundo;
    +string correo;

    +Personaje() = default;
    +Personaje(string nombre): nombre(nombre);
    +virtual Personaje* clone() = 0;
   }

   Class Princesa{
     +Princesa(string n): Personaje(n);
     +Princesa(const Princesa& p);

     +void grita();
     +Personaje* clone();
   }

   Class Villano{
    +Villano(string n): Personaje(n);
    +Villano(const Villano& v);

    +void secuestra();
    +Personaje* clone();
  }

  Class Heroe{
    +Heroe(string n): Personaje(n);
    +Heroe(const Heroe& h);

    +void salvar();
    +Personaje* clone()
  }
    Mundo --* Personaje
    Personaje <|.. Princesa
    Personaje <|.. Villano
    Personaje <|.. Heroe

@enduml
