@startuml
    Class Singleton <<static>>{
        +static Singleton* getInstance();
        +void operation();

        #static Singleton* instance;

        -Singleton(){}
    }

    Singleton <--* Singleton

@enduml
