@startuml
left to right direction
skinparam packageStyle rectangle
actor Osbert
actor Vendedor

  rectangle Sistema_Cuadros {
    Osbert --> (Compra de cuadros)
    (Venta de cuadros) <-- Vendedor
    (Generacion de reportes) <-- Vendedor
  }

@enduml
