/' ACTIVIDAD 1 - Diagramas de clases
Nombre: Daniela Flores Javier
Matrícula: A01023226'/

@startuml
  Class Compra{
    -string ID_compra;
    -date fecha;
    -Vendedor vendedor;
    -Obras obra;
    -float precio_compra;

    +Compra();
    +void calcular_precio();
    +void generar_reporte();
  }

  Class Venta{
    -string ID_venta;
    -date fecha;
    -Cliente cliente;
    -Obras obra;
    -int cantidad;
    -float precio_venta;

    +Venta();
    +void calcular_precio();
    +void generar_reporte();
  }

  Class Cliente{
    -string nombre;
    +Cliente();
  }

  Class Vendedor{
    -string ID_vendedor;
    -string nombre;
    -string direccion_vendedor;
    -bool oferta_obra;
    +Vendedor();
  }

  Class Obras{
    -string ID_obra;
    -string nombre;
    -string tipo_obra;
    -string artista;
    -float precio;
    -int anio_venta;

    +Obras();
  }

  Class Almacen{
    -string ID_almacen;
    -Obras obra;

    +Almacen();
    +alta_inv();
    +baja_inv();
    +consulta_inv();
  }

  Almacen *-- Obras : guarda
  Compra --o Almacen : almacena
  Venta --o Almacen : tiene
  Vendedor -- Compra : acuerda
  Cliente -- Venta : genera
@enduml
