/' ACTIVIDAD 1 - Diagramas de clases
Nombre: Daniela Flores Javier
Matrícula: A01023226'/

@startuml
  Class Compra{
    -string ID_compra;
    -date fecha;
    -Obras obra;
    -float cantidad;
    -float precio_compra;

    +Compra();
    +void calcular_precio();
    +void generar_reporte();
  }

  Class Cliente{
    -string nombre;

    +Cliente();
  }

  Class Venta{
    -string ID_venta;
    -date fecha;
    -Vendedor vendedor;
    -Obras obra;
    -int cantidad;
    -float precio_venta;

    +Venta();
  }

  Class Vendedor{
    -string ID_vendedor;
    -string nombre;
    -string direccion_vendedor;

    +Vendedor();
  }

  Class Obras{
    -string ID_obra;
    -string nombre;
    -string tipo_obra;
    -string artista;
    -float precio;
    -int anio_venta;

    +Obras();
  }

  Class Almacen{
    -string id_almacen;

    +Almacen();
    +alta_inv();
    +baja_inv();
    +consulta_inv();
  }

  Almacen -- Obras : guarda
  Compra *-- Obras : contiene
  Venta -- Almacen : tiene
  Vendedor -- Venta : realiza
  Cliente -- Venta : genera
@enduml
